FROM maven:3.9.9-amazoncorretto-21-alpine AS build

WORKDIR /app

COPY pom.xml .
COPY api/pom.xml ./api/pom.xml
COPY domain/pom.xml ./domain/pom.xml

RUN mvn dependency:go-offline

COPY . .

RUN mvn clean package -DskipTests

FROM amazoncorretto:21-alpine

WORKDIR /app

COPY --from=build /app/api/target/*.jar ./app.jar

ENTRYPOINT ["java","-jar","app.jar"]